learn_python/learn_Django/rsvp/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.LoginView, name='login'),
    url(r'^loginhandle$', views.LoginHandleView, name='loginhandle'),
    url(r'^(?P<user_id>[0-9]+)/event/$', views.EventView, name='event'),
    url(r'^(?P<user_id>[0-9]+)/eventcreate/$', views.EventCreateView, name='eventcreate'),
    url(r'^(?P<user_id>[0-9]+)/eventmodify/$', views.EventModifyView, name='eventmodify'),
    url(r'^questionFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.QuestionView, name='question'),
    url(r'^questioncreateFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.QuestionCreateView, name='questioncreate'),
    url(r'^questionmodifyFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.QuestionModifyView, name='questionmodify'),
    url(r'^answerFor(?P<event_id>[0-9]+)/(?P<question_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.AnswerView, name='answer'),
    url(r'^answercreateFor(?P<event_id>[0-9]+)/(?P<question_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.AnswerCreateView, name='answercreate'),
    url(r'^answermodifyFor(?P<event_id>[0-9]+)/(?P<question_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.AnswerModifyView, name='answermodify'),
    url(r'^clearanswerFor(?P<event_id>[0-9]+)/(?P<question_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.ClearAnswerView, name='clearanswer'),
    url(r'^eventuserFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.EventUserView, name='eventuser'),
    url(r'^eventusercreateFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.EventUserCreateView, name='eventusercreate'),
    url(r'^eventusermodifyFor(?P<event_id>[0-9]+)/(?P<user_id>[0-9]+)/$', views.EventUserModifyView, name='eventusermodify'),
               
]

learn_python/learn_Django/rsvp/rsvp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

learn_python/learn_Django/rsvp/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Event(models.Model):
    e_name = models.CharField(max_length=200)
    e_time = models.DateTimeField('event')
    e_date = models.CharField(max_length=200, default='Unknown')
    def __str__(self):
        return self.e_name

class Question(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)    
    q_time = models.DateTimeField('question published')
    q_text = models.CharField(max_length=200)
    q_type = models.IntegerField(default=0)
    def __str__(self):
        return self.q_text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    a_time = models.DateTimeField('answer posted')
    a_text = models.CharField(max_length=200)
    a_vote = models.IntegerField(default=0)
    a_type = models.IntegerField(default=0)
    def __str__(self):
        return self.a_text

class User(models.Model):
    #u_type = models.IntegerField(default=1)
    u_email = models.CharField(max_length=200, default='null')
    u_name = models.CharField(max_length=200)
    def __str__(self):
        return self.u_name

class Pri_Event(models.Model):
    u = models.ForeignKey(User, related_name='peu_set', on_delete=models.CASCADE)
    e = models.ForeignKey(Event, related_name='pee_set', on_delete=models.CASCADE)
    pe_type = models.IntegerField(default=1)

class Pri_Answer(models.Model):
    u = models.ForeignKey(User, related_name='pau_set', on_delete=models.CASCADE)
    a = models.ForeignKey(Answer, related_name='paa_set', on_delete=models.CASCADE)
    pa_type = models.IntegerField(default=1)

learn_python/learn_Django/rsvp/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Answer, Event, User, Pri_Event, Pri_Answer
from datetime import datetime
from django.core.mail import send_mail
import smtplib

# Create your views here.

def LoginView(request):
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return render(request, 'polls/login.html')

def LoginHandleView(request):
    if ('username' in request.POST and (len(request.POST['username']) > 0)):
        if ('buttonlogin' in request.POST and User.objects.filter(u_name = request.POST['username'])):
            user = get_object_or_404(User, u_name=request.POST['username'])
            request.session['user_id'] = str(user.id)
            return HttpResponseRedirect(reverse('polls:event', args=(user.id, )))
        if ('buttonsign' in request.POST and (not User.objects.filter(u_name = request.POST['username'])) and 'useremail' in request.POST and (len(request.POST['useremail']) > 0)):
            n_user = User(u_email=request.POST['useremail'], u_name=request.POST['username'])
            n_user.save()
    return HttpResponseRedirect(reverse('polls:login', args=()))

def EventView(request, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    event_list = Event.objects.filter(pee_set__u_id=user_id).order_by('-e_time')
    return render(request, 'polls/event.html', {
                  'event_list': event_list,
                  'user_id': user_id,
                  'user_name': get_object_or_404(User, pk=user_id).u_name,
                  'pe_list': get_object_or_404(User, pk=user_id).peu_set.all(),
                  })

def EventCreateView(request, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    user = get_object_or_404(User, pk=user_id)
    if ('eventname_new' in request.POST and (len(request.POST['eventname_new']) > 0)):
        n_event_date = 'Unknown'
        if ('eventdate_new' in request.POST and (len(request.POST['eventdate_new']) > 0)):
            n_event_date = request.POST['eventdate_new']
        n_event = Event(e_name=request.POST['eventname_new'], e_time=timezone.now(), e_date=n_event_date)
        n_event.save()
        n_pe = Pri_Event(u=user, e=n_event, pe_type=0)
        n_pe.save(force_insert=True)
    return HttpResponseRedirect(reverse('polls:event', args=(user_id, )))

def EventModifyView(request, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    user = get_object_or_404(User, pk=user_id)
    for temp in request.POST.items():
        print (temp)
    for e in Event.objects.all():
        if (('eventname' + str(e.id)) in request.POST and (len(request.POST['eventname' + str(e.id)]) > 0) and (get_object_or_404(Pri_Event, u_id=user_id, e_id=e.id).pe_type == 0)):
            e.e_name = request.POST['eventname' + str(e.id)]
        if ('eventdate' + str(e.id)) in request.POST and (len(request.POST['eventdate' + str(e.id)]) > 0) and (get_object_or_404(Pri_Event, u_id=user_id, e_id=e.id).pe_type == 0):
            e.e_date = request.POST['eventdate' + str(e.id)]
        e.save()
    return HttpResponseRedirect(reverse('polls:event', args=(user_id, )))

def QuestionView(request, event_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    event = get_object_or_404(Event, pk=event_id)
    question_list = event.question_set.order_by('-q_time')
    return render(request, 'polls/question.html', {
                  'question_list': question_list,
                  'event_id': event_id,
                  'user_id': user_id,
                  'user_name': get_object_or_404(User, pk=user_id).u_name,
                  'event_name': get_object_or_404(Event, pk=event_id).e_name,
                  })

def QuestionCreateView(request, event_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    user = get_object_or_404(User, pk=user_id)
    event = get_object_or_404(Event, pk=event_id)
    if ('questiontext_new' in request.POST and (len(request.POST['questiontext_new']) > 0) and get_object_or_404(Pri_Event, e_id=event.id, u_id=user.id).pe_type == 0):
        questiontype_new = 0
        if ('questiontype_new' in request.POST and len(request.POST['questiontype_new']) > 0):
            questiontype_new = int(request.POST['questiontype_new'])
        event.question_set.create(q_text=request.POST['questiontext_new'], q_time=timezone.now(), q_type=questiontype_new)
    return HttpResponseRedirect(reverse('polls:question', args=(event_id, user_id, )))


def QuestionModifyView(request, event_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    user = get_object_or_404(User, pk=user_id)
    event = get_object_or_404(Event, pk=event_id)
    for temp in request.POST.items():
        print (temp)
    for q in Question.objects.all():
        if (('questiontext' + str(q.id)) in request.POST and (len(request.POST['questiontext' + str(q.id)]) > 0) and get_object_or_404(Pri_Event, e_id=event.id, u_id=user.id).pe_type == 0):
            mailed_user_set = set()
            for answer in q.answer_set.all():
                for pa in answer.paa_set.all():
                    for mailed_user in User.objects.filter(pau_set__u_id=pa.u_id):
                        mailed_user_set.add(mailed_user)
            for mailed_user in mailed_user_set:
                gmail_user = 'qsxyh123@163.com'
                gmail_pwd = 'ece590rsvp'
                TO = mailed_user.u_email
                SUBJECT = 'Event "' + event.e_name + '" Question "' + q.q_text + '" Change for ' + mailed_user.u_name
                TEXT = 'Question Become ' + request.POST['questiontext' + str(q.id)]
                server = smtplib.SMTP_SSL('smtp.163.com', 465)
                server.login(gmail_user, gmail_pwd)
                BODY = '\r\n'.join(['To: %s' % TO, 'From: %s' % gmail_user,'Subject: %s' % SUBJECT,'', TEXT])
                try:
                    server.sendmail(gmail_user, [TO], BODY)
                except Exception:
                    pass
            q.q_text = request.POST['questiontext' + str(q.id)]
        if (('questiontype' + str(q.id)) in request.POST and len(request.POST['questiontype' + str(q.id)]) > 0 and get_object_or_404(Pri_Event, e_id=event.id, u_id=user.id).pe_type == 0):
            q.q_type = int(request.POST['questiontype' + str(q.id)])
        q.save()
    return HttpResponseRedirect(reverse('polls:question', args=(event_id, user_id, )))

def AnswerView(request, event_id, question_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    question = get_object_or_404(Question, pk=question_id)
    user = get_object_or_404(User, pk=user_id)
    pe = get_object_or_404(Pri_Event, e_id=event_id, u_id=user_id)
    if (pe.pe_type == 0 or pe.pe_type == 1 and question.q_type == 1):
        answer_list = question.answer_set.all()
    elif (pe.pe_type == 1):
        answer_list = question.answer_set.filter(paa_set__u_id=user_id)
    else:
        answer_list = question.answer_set.filter(paa_set__pa_type=2)
    return render(request, 'polls/answer.html', {
                  'event_id': event_id,
                  'question': question,
                  'answer_list': answer_list,
                  'user': user,
                  'pe_type': pe.pe_type,
                  })

def AnswerCreateView(request, event_id, question_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    question = get_object_or_404(Question, pk=question_id)
    pe = get_object_or_404(Pri_Event, e_id=event_id, u_id=user_id)
    user = get_object_or_404(User, pk=user_id)
    if ('answer_text' in request.POST and len(request.POST['answer_text']) > 0 and pe.pe_type == 0):
        n_answer = question.answer_set.create(a_time=timezone.now(), a_text=request.POST['answer_text'], a_vote=1)
        n_pa = Pri_Answer(u=user, a=n_answer, pa_type=pe.pe_type)
        n_pa.save(force_insert=True)
    return HttpResponseRedirect(reverse('polls:answer', args=(event_id, question_id, user_id)))

def AnswerModifyView(request, event_id, question_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    question = get_object_or_404(Question, pk=question_id)
    pe = get_object_or_404(Pri_Event, e_id=event_id, u_id=user_id)
    user = get_object_or_404(User, pk=user_id)
    for a in question.answer_set.all():
        if (('finalize' + str(a.id)) in request.POST):
            a.a_type = 1
        if (('answer_text' + str(a.id)) in request.POST and len(request.POST['answer_text' + str(a.id)]) > 0 and a.a_type == 0):
            a.a_text = request.POST['answer_text' + str(a.id)]
        if (('answer' + str(a.id)) in request.POST and a.a_type == 0):
            a.a_vote += 1
        a.save()
        if (('permission' + str(a.id)) in request.POST):
            n_pa = Pri_Answer(u=user, a=a, pa_type=2)
            n_pa.save(force_insert=True)
    return HttpResponseRedirect(reverse('polls:answer', args=(event_id, question_id, user_id)))

def ClearAnswerView(request, event_id, question_id, user_id):
    if (request.session.get('user_id', 0) != user_id):
        return HttpResponseRedirect(reverse('polls:login', args=()))
    question = get_object_or_404(Question, pk=question_id)

learn_python/learn_Django/rsvp/polls/templates/polls/answer.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/back.css' %}" />
<h1>Answer List of User "{{ user.u_name }}" for Question "{{ question.q_text }}" </h1>
<div id="event_frame">

<form action="{% url 'polls:answermodify' event_id question.id user.id %}" method="post">
  {% csrf_token %} 
  {% for a in answer_list %}
  <fieldset>
    <legend>Answer {{ forloop.counter }}</legend>
    <li>{{ a.a_text }} -- {{ a.a_vote }} vote{{ a.a_vote|pluralize }} --
        {% if a.a_type == 1 %}
        Already Finilized
        {% endif %}
        </li>
    {% if pe_type < 2 %}
        <input type="text" name="answer_text{{ a.id }}" id="box{{ forloop.counter }}">
        <input type="checkbox" name="answer{{ a.id }}">+ 1<br>
    {% endif %}
    {% if pe_type == 0 %}
        <input type="checkbox" name="permission{{ a.id }}">Vendor Permission
    {% endif %}
    {% if pe_type == 0 or pe_type == 2 %}
        <input type="checkbox" name="finalize{{ a.id }}">Finalize<br>
    {% endif %}
  </fieldset>
  {% endfor %}
  <input type="submit" value="Modify it" />
</form>

{% if question.q_type == 0 and pe_type < 2 or pe_type == 0 %}
<form action="{% url 'polls:answercreate' event_id question.id user.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>Create New Answer</legend>
    <input type="text" name="answer_text"
      id="box">
  </fieldset>

  <input type="submit" value="Submit" />
</form>
{% endif %}

{% if pe_type == 0 %}
<form action="{% url 'polls:clearanswer' event_id question.id user.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Clear" />
</form>
{% endif %}
<form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
</form>
<form action="{% url 'polls:question' event_id user.id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Back" />
</form>
</div>

learn_python/learn_Django/rsvp/polls/templates/polls/event.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/back.css' %}" />

<div id="event_frame">
<h1>Event list of User "{{ user_name }}" </h1>

<form action="{% url 'polls:eventmodify' user_id %}" method="post">
    {% csrf_token %}
    {% for e in event_list %}
    <fieldset>
        <legend>Event {{ forloop.counter }}</legend>
        <li><a href="{% url 'polls:question' e.id user_id%}">{{ e.e_name }} -- {{ e.e_date }} --
            {% for pe in pe_list %}
                {% if pe.pe_type == 0 and pe.e_id == e.id %}
                    Owner
                {% elif pe.pe_type == 1 and pe.e_id == e.id %}
                    Guest
                {% elif pe.e_id == e.id %}
                    Vendor
                {% endif %}
            {% endfor %}
        </a></li>
        <label for="box1{{ forloop.counter }}">Event Name</label><br>
        <input type="text" name="eventname{{ e.id }}" id="box1{{ forloop.counter }}"><br>
        <label for="box2{{ forloop.counter }}">Event Time</label><br>
        <input type="text" name="eventdate{{ e.id }}" id="box2{{ forloop.counter }}"><br>
        <a href="{% url 'polls:eventuser' e.id user_id%}">Manage Users of Event {{ forloop.counter }}</a>
    </fieldset>
    {% endfor %}
    {% if event_list %}
    <input type="submit" value="Modify it" />
    {% endif %}
</form>

<form action="{% url 'polls:eventcreate' user_id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Create New Event</legend>
        <label for="box1">Name</label><br>
        <input type="text" name="eventname_new" id="box1"><br>
        <label for="box2">Time</label><br>
        <input type="text" name="eventdate_new" id="box2">
    </fieldset>
    <input type="submit" value="Create it" />
</form>
<form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
</form>
</div>

learn_python/learn_Django/rsvp/polls/templates/polls/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/login.css' %}" />

<div id="login_frame">
<h1>User Login</h1>
<form action="{% url 'polls:loginhandle' %}", method="post">
  {% csrf_token %}
  <label for="box1">User Name</label><br>
  <input type="text" name="username" id="box1"><br>
  <label for="box1">User Email</label><br>
  <input type="text" name="useremail" id="box"><br>
  <input type="submit" name="buttonlogin" value="Login" />
  <input type="submit" name="buttonsign" value="Sign Up" />
</form>
</div>

learn_python/learn_Django/rsvp/polls/templates/polls/question.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/back.css' %}" />
<div id="event_frame">
<h1>Question List of User "{{ user_name }}" for Event "{{ event_name }}"</h1>

<form action="{% url 'polls:questionmodify' event_id user_id%}" method="post">
    {% csrf_token %}
    {% for q in question_list %}
    <fieldset>
        <legend>Question {{ forloop.counter }}</legend>
        <li><a href="{% url 'polls:answer' event_id q.id user_id%}">{{ q.q_text }} --
            {% if q.q_type == 0 %}
            Free Text
            {% else %}
            Multiple Choices
            {% endif %}
        </a></li>
        <input type="text" name="questiontext{{ q.id }}" id="box{{ forloop.counter }}">
        <input type="radio" name="questiontype{{ q.id }}" id="c0{{ forloop.counter }}" value="0">
        <label for="c0{{ forloop.counter }}">Free Text</label>
        <input type="radio" name="questiontype{{ q.id }}" id="c1{{ forloop.counter }}" value="1">
        <label for="c1{{ forloop.counter }}">Multiple Choices</label>
    </fieldset>
    {% endfor %}
    {% if question_list %}
    <input type="submit" value="Modify it" />
    {% endif %}
</form>

<form action="{% url 'polls:questioncreate' event_id user_id%}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Create New Question</legend>
        <input type="text" name="questiontext_new" id="box">
        <input type="radio" name="questiontype_new" id="c0" value="0">
        <label for="c0">Free Text</label>
        <input type="radio" name="questiontype_new" id="c1" value="1">
        <label for="c1">Multiple Choices</label>
    </fieldset>
    <input type="submit" value="Create it" />
</form>
<form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
</form>
<form action="{% url 'polls:event' user_id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Back" />
</form>
</div>

learn_python/learn_Django/rsvp/polls/templates/polls/user.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/back.css' %}" />

<div id="event_frame">
<h1>User List</h1>

<form action="{% url 'polls:eventusermodify' event_id user_id %}" method="post">
  {% csrf_token %}
  {% for u in user_list %}
  <fieldset>
    <legend>User {{ forloop.counter }}</legend>
    <li>{{ u.u_name }} --
        {% for pe in pe_list %}
            {% if pe.pe_type == 0 and pe.u_id == u.id %}
                Owner
            {% elif pe.pe_type == 1 and pe.u_id == u.id %}
                Guest
            {% elif pe.u_id == u.id %}
                Vendor
            {% endif %}
        {% endfor %}
    </li>
    <input type="radio" name="usertype{{ u.id }}" id="c0{{ forloop.counter }}" value="0">
    <label for="c0{{ forloop.counter }}">Owner</label>
    <input type="radio" name="usertype{{ u.id }}" id="c1{{ forloop.counter }}" value="1">
    <label for="c1{{ forloop.counter }}">Guest</label>
    <input type="radio" name="usertype{{ u.id }}" id="c2{{ forloop.counter }}" value="2">
    <label for="c2{{ forloop.counter }}">Vendor</label>
  </fieldset>
  {% endfor %}
  {% if user_list %}
    <input type="submit" value="Modify it" />
  {% endif %}
</form>

<form action="{% url 'polls:eventusercreate' event_id user_id %}" method="post">
    {% csrf_token %}
  <fieldset>
    <legend>Create New User</legend>
    <input type="text" name="username_new" id="box">
    <input type="radio" name="usertype_new" id="c0" value="0">
    <label for="c0">Owner</label>
    <input type="radio" name="usertype_new" id="c1" value="1">
    <label for="c1">Guest</label>
    <input type="radio" name="usertype_new" id="c2" value="2">
    <label for="c2">Vendor</label>
  </fieldset>
  <input type="submit" value="Create it" />
</form>
<form action="{% url 'polls:login' %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Logout" />
</form>
<form action="{% url 'polls:event' user_id %}" method="get">
    {% csrf_token %}
    <input type="submit" value="Back" />
</form>
</div>